// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseWindow():Promise<void>;

export function GetImageColor(arg1:string):Promise<main.ColorResult>;

export function GetServerIcon(arg1:string):Promise<string>;

export function IsMaximized():Promise<boolean>;

export function MaximizeWindow():Promise<void>;

export function MinimizeWindow():Promise<void>;

export function StartGame(arg1:string,arg2:Array<string>):Promise<void>;
