// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function GetImageColor(arg1) {
  return window['go']['main']['App']['GetImageColor'](arg1);
}

export function GetServerIcon(arg1) {
  return window['go']['main']['App']['GetServerIcon'](arg1);
}

export function IsMaximized() {
  return window['go']['main']['App']['IsMaximized']();
}

export function MaximizeWindow() {
  return window['go']['main']['App']['MaximizeWindow']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function StartGame(arg1, arg2) {
  return window['go']['main']['App']['StartGame'](arg1, arg2);
}
