// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseWindow():Promise<void>;

export function DownloadFiles(arg1:string):Promise<void>;

export function GetConfig():Promise<main.Config>;

export function GetImageColor(arg1:string):Promise<main.ColorResult>;

export function GetSavedStartCfgs():Promise<Array<main.StartCfg>>;

export function GetStyleFile(arg1:string):Promise<Array<number>>;

export function GetUpdates(arg1:string):Promise<main.ComparisonResult>;

export function IsMaximized():Promise<boolean>;

export function IsUpdateAvailable(arg1:string):Promise<boolean>;

export function MaximizeWindow():Promise<void>;

export function MinimizeWindow():Promise<void>;

export function OpenFolderDialog():Promise<string>;

export function OpenFolderDialogWithDefault(arg1:string):Promise<string>;

export function RemoveSavedStartCfg(arg1:number):Promise<void>;

export function StartGame(arg1:string,arg2:Array<string>):Promise<void>;

export function StopDownloads():Promise<boolean>;

export function UpdateConfig(arg1:main.Config):Promise<void>;
