// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function DownloadFiles(arg1) {
  return window['go']['main']['App']['DownloadFiles'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetImageColor(arg1) {
  return window['go']['main']['App']['GetImageColor'](arg1);
}

export function GetSavedStartCfgs() {
  return window['go']['main']['App']['GetSavedStartCfgs']();
}

export function GetServerIcon(arg1) {
  return window['go']['main']['App']['GetServerIcon'](arg1);
}

export function GetUpdates(arg1) {
  return window['go']['main']['App']['GetUpdates'](arg1);
}

export function IsMaximized() {
  return window['go']['main']['App']['IsMaximized']();
}

export function IsUpdateAvailable(arg1) {
  return window['go']['main']['App']['IsUpdateAvailable'](arg1);
}

export function MaximizeWindow() {
  return window['go']['main']['App']['MaximizeWindow']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function OpenFolderDialogWithDefault(arg1) {
  return window['go']['main']['App']['OpenFolderDialogWithDefault'](arg1);
}

export function RemoveSavedStartCfg(arg1) {
  return window['go']['main']['App']['RemoveSavedStartCfg'](arg1);
}

export function StartGame(arg1, arg2) {
  return window['go']['main']['App']['StartGame'](arg1, arg2);
}

export function StopDownloads() {
  return window['go']['main']['App']['StopDownloads']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
